# Generated by Django 5.0.4 on 2024-07-27 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="img",
            field=models.ImageField(
                default="https://letsenhance.io/static/8f5e523ee6b2479e26ecc91b9c25261e/6e61b/MainAfter.avif",
                upload_to="images/",
            ),
            preserve_default=False,
        ),
    ]
