# Generated by Django 5.0.4 on 2024-07-27 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0002_post_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="img",
            field=models.ImageField(
                default="images/coming_soon.jpg", upload_to="images/"
            ),
        ),
    ]
